version: "3.7"

volumes:
  certs:
  vhost:
  html:
  acme:

services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${DOMAIN}
    expose:
      - "8080"

  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - NGINX_HOST=${DOMAIN}
      - NGINX_PORT=80

  ssl:
    image: nginxproxy/acme-companion
    volumes_from:
      - proxy:rw
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${EMAIL}
