# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Cache Node dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build and unit tests with Maven
      run: ./mvnw -Djavacpp.platform=linux-x86_64 clean verify

    - name: Clean up node directory
      run: rm -rf target/node
    - run: rm -rf target/*.jar*

    - uses: actions/upload-artifact@master
      with:
        name: multijsnake
        path: target/
        retention-days: 1

  jacoco:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: multijsnake
        path: target/

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: target/site/jacoco-aggregate/jacoco.csv
        badges-directory: ./

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: backend-coverage-report
        path: target/site/jacoco-aggregate/

    - name: Upload Badge
      uses: actions/upload-artifact@v2
      with:
        name: backend-coverage-badge
        path: jacoco.svg

  python:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@master
      with:
        name: multijsnake
        path: target/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2

    - name: Run one training iteration
      run: cd src/main/py ; python train_AC.py --test ; python train_convAC.py --test

  cypress-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: multijsnake
        path: target/

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: install node
      uses: actions/setup-node@v2
    - run: npm install

    - name: Instrument js for cypress coverage
      run: npm run debug

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: mvn -DskipTests -Dskip.npm -Djavacpp.platform=linux-x86_64 spring-boot:run

    - name: Upload Istanbul coverage report
      uses: actions/upload-artifact@v2
      with:
        name: frontend-coverage-report
        path: target/cypress-coverage/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: get badge
      run: python3 coverage2badge.py

    - name: Upload Badge
      uses: actions/upload-artifact@v2
      with:
        name: frontend-coverage-badge
        path: frontend_coverage.svg

  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install node
      uses: actions/setup-node@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: build static site
      run: bash buildStatic.sh

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: tmp/
        start: python3 -m http.server 8080 -d resources/static/

  publish-coverage:
    needs: [jacoco, cypress-coverage]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: frontend-coverage-report
        path: frontend/

    - uses: actions/download-artifact@master
      with:
        name: backend-coverage-report
        path: backend/

    - uses: actions/download-artifact@master
      with:
        name: frontend-coverage-badge
        path: badges/

    - uses: actions/download-artifact@master
      with:
        name: backend-coverage-badge
        path: badges/

    - run: echo "<p><a href='frontend/lcov-report/index.html'>Frontend</a></p>" > index.html
    - run: echo "<p><a href='backend/index.html'>Backend</a></p>" >> index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true
